# UrbanPulse AI

# Data Preprocessing

## Objective

Prepare the complaint dataset for Machine Learning, NLP, Dashboarding, and AI model development by performing data cleaning, feature engineering, and preprocessing.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../data/complaints/bbmp_2024.csv")

df.head()

,Complaint ID,Category,Sub Category,Grievance Date,Ward Name,Grievance Status,Staff Remarks,Staff Name
0,20644646,Solid Waste (Garbage) Related,Garbage vehicle not arrived,2024-12-31 05:52:00.000000000,Manorayanapalya,Closed,Clear,Nagendra/JHI
1,20644640,Electrical,Street Light Not Working,2024-12-31 11:36:00.000000000,Basavanapura,Closed,Attended,Sachin Malagi/AE
2,20644639,Electrical,Street Light Not Working,2024-12-31 11:24:00.000000000,Maruthi Seva Nagar,Closed,Attended,Durga Prasad/AEE
3,20644638,Electrical,Street Light Not Working,2024-12-31 11:21:00.000000000,Aramane Nagar,Closed,Complaints Cleared,Suresh/AEE
4,20644637,Electrical,Street Light Not Working,2024-12-31 11:00:00.000000000,Vidyaranyapura,Closed,Resolved,Yelahanka AEE Electrical/AEE

In [3]:
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

df.head()

,complaint_id,category,sub_category,grievance_date,ward_name,grievance_status,staff_remarks,staff_name
0,20644646,Solid Waste (Garbage) Related,Garbage vehicle not arrived,2024-12-31 05:52:00.000000000,Manorayanapalya,Closed,Clear,Nagendra/JHI
1,20644640,Electrical,Street Light Not Working,2024-12-31 11:36:00.000000000,Basavanapura,Closed,Attended,Sachin Malagi/AE
2,20644639,Electrical,Street Light Not Working,2024-12-31 11:24:00.000000000,Maruthi Seva Nagar,Closed,Attended,Durga Prasad/AEE
3,20644638,Electrical,Street Light Not Working,2024-12-31 11:21:00.000000000,Aramane Nagar,Closed,Complaints Cleared,Suresh/AEE
4,20644637,Electrical,Street Light Not Working,2024-12-31 11:00:00.000000000,Vidyaranyapura,Closed,Resolved,Yelahanka AEE Electrical/AEE

## Why rename columns?

Using lowercase column names with underscores improves readability and follows industry-standard naming conventions.

In [4]:
df["grievance_date"] = pd.to_datetime(df["grievance_date"])

In [5]:
df["year"] = df["grievance_date"].dt.year
df["month"] = df["grievance_date"].dt.month
df["day"] = df["grievance_date"].dt.day
df["day_name"] = df["grievance_date"].dt.day_name()